### ISSUE TITLE
Allow generic option vars pass through to Net::Server

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/Starman#109]
I'd like to keep the root option namespace to specific for plackup common variables, but it would make sense to allow some prefixed options passed through to Net::Server, such as:

    starman --net_server-lock_file=/tmp/file.lock ...

or some sort.

**Comment by ap** [comment]
Maybe just `--ns-` as prefix? Or `--nsrv-` maybe? Not sure what would be good… but `--net_server-` is awfully long.

**Comment by miyagawa** [comment]
I'd think that hey're meant to be scripted in your launcher script (init.d etc) and not for the regular command line use.

**Comment by miyagawa** [comment]
in other words, if they're commonly used, we should just give a shortcut like the current ones (keepalive, etc.)

**Comment by ap** [comment]
This was implemented by #111, which has been merged and shipped, so the issue can be closed.
