### ISSUE TITLE
POSIX::setgid not implemented on this architecture

### ISSUE THREAD

**Issue by abutun** [miyagawa/Starman#126]
I am trying to execute below command in order to serve my web application (Dancer2)

plackup --server Starman --host 0.0.0.0 --port 80 -E production --workers=100 app.psgi

and it gives me this error:

2017/09/09-20:35:59 Starman::Server (type Net::Server::PreFork) starting! pid(1216)
Binding to TCP port 80 on host 0.0.0.0 with IPv4
Setting gid to "0 0"
2017/09/09-20:35:59 POSIX::setgid not implemented on this architecture at C:/Strawberry/perl/site/lib/Net/Server/Daemonize.pm line 156, <DATA> line 1.

  at line 392 in file C:/Strawberry/perl/site/lib/Net/Server.pm
2017/09/09-20:35:59 Received QUIT. Running a graceful shutdown
2017/09/09-20:35:59 Worker processes cleaned up
2017/09/09-20:35:59 Server closing!

any help?

**Comment by dex4er** [comment]
@abutub Starman and most of PSGI servers don't work on Windows because on this system there is no `fork` system function. You can try https://github.com/dex4er/Thrall which uses threads instead even if threading in Perl is not perfect. Or use Twiggy if you have non-blocking procedures in your app.
