### ISSUE TITLE
Document the use of rand() and File::Temp

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/Starman#20]
if you use the application in the parent with `--preload-app` and then use modules that calls rand(), such as File::Temp, and then later in the children again, your child processes get the same stream of rand() because the seed was initialized in the parent.

Does it make sense to call srand() by Starman, or at least should we document that as a known issue? 

See File::Temp/Forking for details.

**Comment by muraiki** [comment]
This was resolved in version 0.2009, correct?

**Comment by miyagawa** [comment]
Yes.

**Comment by muraiki** [comment]
速いですね！　サンキュー
