### ISSUE TITLE
Support for sig_passthrough option of Net::Server

### ISSUE THREAD

**Issue by wreis** [miyagawa/Starman#68]
Hi,
I couldn't find any way to set sig_passthrough option for Net::Server out of box. Please advise if there is any known path, otherwise I will be happy to try and do a patch.

**Comment by oschwald** [comment]
We also ran into a similar situation where it would be very useful to set `sig_passthrough` for an internal use of SIGUSR1.

**Comment by miyagawa** [comment]
#111 added passing through Net::Server options with the `--net_server-` prefix (or via directly creating Starman::Server instance). Does that work for you?

**Comment by oschwald** [comment]
Yes, it does. Thanks! The prefix seems to be `--net_server_` rather than `--net_server-` though.

**Comment by miyagawa** [comment]
No, it is `--net_server-`. (It actually accepts both)

**Comment by oschwald** [comment]
Ah, ok. I just looked at the diff. I didn't realize Plack::Runner mangled the params before that point.
